---
- name: Cleanup neovim downloaded tar
  ansible.builtin.file:
    path: "/tmp/{{ nvim_file }}.tar.gz"
    state: absent
  become: true

- name: Remove extracted neovim directory
  ansible.builtin.file:
    path: /tmp/{{ nvim_file }}
    state: absent
  become: true