---
- name: "Nala | Detecting Installed Nala"
  ansible.builtin.command:
    cmd: which nala
  changed_when: false
  register: nala_cmd
  failed_when: false

- name: "Nala | Register nala status installed"
  ansible.builtin.set_fact:
    nala_is_installed: true
  when: nala_cmd.stdout|length > 0

- name: "Nala | Register nala status not installed"
  ansible.builtin.set_fact:
    nala_is_installed: false
  when: nala_cmd.stdout|length == 0

- name: "Nala | Install Nala"
  ansible.builtin.apt:
    name: nala
    state: present
  become: true