---
- name: Cleanup node downloaded tar
  ansible.builtin.file:
    path: "/tmp/{{ nodejs_package_name }}.tar.xz"
    state: absent
  become: true

- name: Remove extracted node directory
  ansible.builtin.file:
    path: /tmp/{{ nodejs_package_name }}
    state: absent
  become: true