---
- name: Run Neovim Tasks for Zorin
  ansible.builtin.import_tasks: zorin.yml
  when: ansible_os_family == 'Zorin OS' or ansible_os_family == 'Ubuntu'

- name: Run Neovim Tasks for Debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'