---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - software-properties-common
    state: present
  become: true

- name: "Neovim | Install"
  community.general.snap:
    name: nvim
    classic: true
    state: present
  become: true

- name: "Neovim | Install NvChad"
  ansible.builtin.git:
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
    depth: 1

- name: "Neovim | Configure NvChad"
  ansible.builtin.copy:
    src: custom
    dest: "{{ ansible_user_dir }}/.config/nvim/lua/"
    mode: 0644
    directory_mode: 0755
    force: true
